# Sample of the augmented config files. It is needed to add augmented_weight in the default file, in order to use it from the main training file.

NAME: 'rap2_bald_augmentation'

DATASET:
  TYPE: 'pedes'
  NAME: 'RAP2'
  TRAIN_SPLIT: 'trainval'
  VAL_SPLIT: 'test'
  ZERO_SHOT: False
  LABEL: 'eval'
  HEIGHT: 256
  WIDTH: 192
  PARTITION: 0 # FOR 0 for 50 percent, 1 for 100 and so on
  DATASET_FILE_NAME: "dataset_RAP2_medium_hs-BaldHead.pkl"

RELOAD:
  TYPE: False
  NAME: 'backbone'

BACKBONE:
  TYPE: 'resnet50'

CLASSIFIER:
  NAME: 'linear'
  POOLING: 'avg'
  SCALE: 1
  BN: False

LOSS:
  TYPE: 'bceloss_augmented'
  LOSS_WEIGHT: [1]
  SAMPLE_WEIGHT: 'weight'
  AUGMENTED_WEIGHT: 0.5

TRAIN:
  CLIP_GRAD: True
  BATCH_SIZE: 16
  OPTIMIZER:
    TYPE: 'adam'
    WEIGHT_DECAY: 5e-4
  LR_SCHEDULER:
    TYPE: 'plateau'
    LR_FT: 0.0001
    LR_NEW: 0.0001
  EMA:
    ENABLE: False

METRIC:
  TYPE: 'pedestrian'

VIS:
  CAM: 'valid'
